\connect ai_gateway_system

INSERT INTO model_profiles (
    id,
    name,
    purpose,
    provider,
    base_url,
    model,
    enabled,
    is_default,
    timeout_ms,
    api_key_configured,
    supports_streaming,
    dimensions,
    top_n,
    default_parameters_json,
    created_by_user_id,
    updated_by_user_id,
    created_at,
    updated_at
)
VALUES
    (
        'default-chat',
        'Local placeholder chat profile',
        'chat',
        'local_compatible',
        'http://host.docker.internal:11434/v1',
        'local-placeholder-chat',
        true,
        true,
        60000,
        true,
        true,
        null,
        null,
        '{"temperature":0.2}'::jsonb,
        'usr_local_admin',
        'usr_local_admin',
        now(),
        now()
    ),
    (
        'default-embedding',
        'Local placeholder embedding profile',
        'embedding',
        'local_compatible',
        'http://host.docker.internal:11434/v1',
        'local-placeholder-embedding',
        true,
        true,
        60000,
        true,
        false,
        384,
        null,
        '{}'::jsonb,
        'usr_local_admin',
        'usr_local_admin',
        now(),
        now()
    ),
    (
        'default-rerank',
        'Local placeholder rerank profile',
        'rerank',
        'local_compatible',
        'http://host.docker.internal:11434/v1',
        'local-placeholder-rerank',
        true,
        true,
        60000,
        true,
        false,
        null,
        5,
        '{}'::jsonb,
        'usr_local_admin',
        'usr_local_admin',
        now(),
        now()
    )
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    provider = EXCLUDED.provider,
    base_url = EXCLUDED.base_url,
    model = EXCLUDED.model,
    enabled = EXCLUDED.enabled,
    is_default = EXCLUDED.is_default,
    timeout_ms = EXCLUDED.timeout_ms,
    api_key_configured = EXCLUDED.api_key_configured,
    supports_streaming = EXCLUDED.supports_streaming,
    dimensions = EXCLUDED.dimensions,
    top_n = EXCLUDED.top_n,
    default_parameters_json = EXCLUDED.default_parameters_json,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_at = now();
