// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: conversations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertConversation = `-- name: InsertConversation :exec
INSERT INTO conversations (
    id,
    external_user_id,
    title,
    status,
    created_at,
    updated_at
) VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertConversationParams struct {
	ID             string    `json:"id"`
	ExternalUserID string    `json:"external_user_id"`
	Title          string    `json:"title"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) error {
	_, err := q.db.Exec(ctx, insertConversation,
		arg.ID,
		arg.ExternalUserID,
		arg.Title,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getConversationAccess = `-- name: GetConversationAccess :one
SELECT
    external_user_id,
    deleted_at
FROM conversations
WHERE id::text = $1::text
`

type GetConversationAccessRow struct {
	ExternalUserID string             `json:"external_user_id"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetConversationAccess(ctx context.Context, id string) (GetConversationAccessRow, error) {
	row := q.db.QueryRow(ctx, getConversationAccess, id)
	var item GetConversationAccessRow
	err := row.Scan(&item.ExternalUserID, &item.DeletedAt)
	return item, err
}

const getConversationForUser = `-- name: GetConversationForUser :one
SELECT
    c.id::text,
    c.title,
    c.external_user_id,
    c.status,
    c.created_at,
    c.updated_at,
    c.last_message_at,
    (
        SELECT count(*)
        FROM messages m
        WHERE m.conversation_id = c.id
    )::bigint AS message_count,
    COALESCE((
        SELECT left(b.content, 200)
        FROM messages m
        JOIN message_content_blocks b
            ON b.message_id = m.id
            AND b.block_order = 0
        WHERE m.conversation_id = c.id
        ORDER BY m.sequence_no DESC
        LIMIT 1
    ), '') AS last_message_preview
FROM conversations c
WHERE c.id::text = $1::text
    AND c.external_user_id = $2
    AND c.deleted_at IS NULL
`

type ConversationSummaryRow struct {
	ID                 string             `json:"id"`
	Title              string             `json:"title"`
	ExternalUserID     string             `json:"external_user_id"`
	Status             string             `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	MessageCount       int64              `json:"message_count"`
	LastMessagePreview string             `json:"last_message_preview"`
}

func (q *Queries) GetConversationForUser(ctx context.Context, id string, externalUserID string) (ConversationSummaryRow, error) {
	row := q.db.QueryRow(ctx, getConversationForUser, id, externalUserID)
	return scanConversationSummaryRow(row)
}

const countConversationsByStatus = `-- name: CountConversationsByStatus :one
SELECT count(*)
FROM conversations
WHERE external_user_id = $1
    AND deleted_at IS NULL
    AND status = $2
`

func (q *Queries) CountConversationsByStatus(ctx context.Context, externalUserID string, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationsByStatus, externalUserID, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listConversationsUpdatedDesc = `-- name: ListConversationsUpdatedDesc :many
SELECT
    c.id::text,
    c.title,
    c.external_user_id,
    c.status,
    c.created_at,
    c.updated_at,
    c.last_message_at,
    (
        SELECT count(*)
        FROM messages m
        WHERE m.conversation_id = c.id
    )::bigint AS message_count,
    COALESCE((
        SELECT left(b.content, 200)
        FROM messages m
        JOIN message_content_blocks b
            ON b.message_id = m.id
            AND b.block_order = 0
        WHERE m.conversation_id = c.id
        ORDER BY m.sequence_no DESC
        LIMIT 1
    ), '') AS last_message_preview
FROM conversations c
WHERE c.external_user_id = $1
    AND c.deleted_at IS NULL
    AND c.status = $2
ORDER BY c.updated_at DESC, c.id DESC
LIMIT $3 OFFSET $4
`

type ListConversationsParams struct {
	ExternalUserID string `json:"external_user_id"`
	Status         string `json:"status"`
	PageSize       int32  `json:"page_size"`
	PageOffset     int32  `json:"page_offset"`
}

func (q *Queries) ListConversationsUpdatedDesc(ctx context.Context, arg ListConversationsParams) ([]ConversationSummaryRow, error) {
	return q.listConversations(ctx, listConversationsUpdatedDesc, arg)
}

const listConversationsUpdatedAsc = `-- name: ListConversationsUpdatedAsc :many
SELECT
    c.id::text,
    c.title,
    c.external_user_id,
    c.status,
    c.created_at,
    c.updated_at,
    c.last_message_at,
    (
        SELECT count(*)
        FROM messages m
        WHERE m.conversation_id = c.id
    )::bigint AS message_count,
    COALESCE((
        SELECT left(b.content, 200)
        FROM messages m
        JOIN message_content_blocks b
            ON b.message_id = m.id
            AND b.block_order = 0
        WHERE m.conversation_id = c.id
        ORDER BY m.sequence_no DESC
        LIMIT 1
    ), '') AS last_message_preview
FROM conversations c
WHERE c.external_user_id = $1
    AND c.deleted_at IS NULL
    AND c.status = $2
ORDER BY c.updated_at ASC, c.id DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListConversationsUpdatedAsc(ctx context.Context, arg ListConversationsParams) ([]ConversationSummaryRow, error) {
	return q.listConversations(ctx, listConversationsUpdatedAsc, arg)
}

const listConversationsCreatedDesc = `-- name: ListConversationsCreatedDesc :many
SELECT
    c.id::text,
    c.title,
    c.external_user_id,
    c.status,
    c.created_at,
    c.updated_at,
    c.last_message_at,
    (
        SELECT count(*)
        FROM messages m
        WHERE m.conversation_id = c.id
    )::bigint AS message_count,
    COALESCE((
        SELECT left(b.content, 200)
        FROM messages m
        JOIN message_content_blocks b
            ON b.message_id = m.id
            AND b.block_order = 0
        WHERE m.conversation_id = c.id
        ORDER BY m.sequence_no DESC
        LIMIT 1
    ), '') AS last_message_preview
FROM conversations c
WHERE c.external_user_id = $1
    AND c.deleted_at IS NULL
    AND c.status = $2
ORDER BY c.created_at DESC, c.id DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListConversationsCreatedDesc(ctx context.Context, arg ListConversationsParams) ([]ConversationSummaryRow, error) {
	return q.listConversations(ctx, listConversationsCreatedDesc, arg)
}

const listConversationsCreatedAsc = `-- name: ListConversationsCreatedAsc :many
SELECT
    c.id::text,
    c.title,
    c.external_user_id,
    c.status,
    c.created_at,
    c.updated_at,
    c.last_message_at,
    (
        SELECT count(*)
        FROM messages m
        WHERE m.conversation_id = c.id
    )::bigint AS message_count,
    COALESCE((
        SELECT left(b.content, 200)
        FROM messages m
        JOIN message_content_blocks b
            ON b.message_id = m.id
            AND b.block_order = 0
        WHERE m.conversation_id = c.id
        ORDER BY m.sequence_no DESC
        LIMIT 1
    ), '') AS last_message_preview
FROM conversations c
WHERE c.external_user_id = $1
    AND c.deleted_at IS NULL
    AND c.status = $2
ORDER BY c.created_at ASC, c.id DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListConversationsCreatedAsc(ctx context.Context, arg ListConversationsParams) ([]ConversationSummaryRow, error) {
	return q.listConversations(ctx, listConversationsCreatedAsc, arg)
}

func (q *Queries) listConversations(ctx context.Context, query string, arg ListConversationsParams) ([]ConversationSummaryRow, error) {
	rows, err := q.db.Query(ctx, query, arg.ExternalUserID, arg.Status, arg.PageSize, arg.PageOffset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]ConversationSummaryRow, 0)
	for rows.Next() {
		item, err := scanConversationSummaryRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

type conversationScanner interface {
	Scan(dest ...any) error
}

func scanConversationSummaryRow(scanner conversationScanner) (ConversationSummaryRow, error) {
	var item ConversationSummaryRow
	err := scanner.Scan(
		&item.ID,
		&item.Title,
		&item.ExternalUserID,
		&item.Status,
		&item.CreatedAt,
		&item.UpdatedAt,
		&item.LastMessageAt,
		&item.MessageCount,
		&item.LastMessagePreview,
	)
	return item, err
}

const updateConversation = `-- name: UpdateConversation :execrows
UPDATE conversations
SET title = $1,
    status = $2,
    updated_at = $3
WHERE id::text = $4::text
    AND external_user_id = $5
    AND deleted_at IS NULL
`

type UpdateConversationParams struct {
	Title          string    `json:"title"`
	Status         string    `json:"status"`
	UpdatedAt      time.Time `json:"updated_at"`
	ID             string    `json:"id"`
	ExternalUserID string    `json:"external_user_id"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (int64, error) {
	tag, err := q.db.Exec(ctx, updateConversation,
		arg.Title,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.ExternalUserID,
	)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

const softDeleteConversation = `-- name: SoftDeleteConversation :execrows
UPDATE conversations
SET deleted_at = now(),
    updated_at = now()
WHERE id::text = $1::text
    AND external_user_id = $2
    AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteConversation(ctx context.Context, id string, externalUserID string) (int64, error) {
	tag, err := q.db.Exec(ctx, softDeleteConversation, id, externalUserID)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
