// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: conversations_extra.sql

package sqlc

import (
	"context"
	"time"
)

const lockConversationForUser = `-- name: LockConversationForUser :one
SELECT true
FROM conversations
WHERE id::text = $1::text
    AND external_user_id = $2
    AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockConversationForUser(ctx context.Context, id string, externalUserID string) (bool, error) {
	row := q.db.QueryRow(ctx, lockConversationForUser, id, externalUserID)
	var value bool
	err := row.Scan(&value)
	return value, err
}

const touchConversationActivity = `-- name: TouchConversationActivity :exec
UPDATE conversations
SET updated_at = $1,
    last_message_at = $2
WHERE id::text = $3::text
`

type TouchConversationActivityParams struct {
	UpdatedAt     time.Time `json:"updated_at"`
	LastMessageAt time.Time `json:"last_message_at"`
	ID            string    `json:"id"`
}

func (q *Queries) TouchConversationActivity(ctx context.Context, arg TouchConversationActivityParams) error {
	_, err := q.db.Exec(ctx, touchConversationActivity, arg.UpdatedAt, arg.LastMessageAt, arg.ID)
	return err
}
