// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessagesForConversation = `-- name: CountMessagesForConversation :one
SELECT count(*)
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE m.conversation_id::text = $1::text
    AND c.external_user_id = $2
    AND c.deleted_at IS NULL
`

func (q *Queries) CountMessagesForConversation(ctx context.Context, conversationID string, externalUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesForConversation, conversationID, externalUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMessagesForConversation = `-- name: ListMessagesForConversation :many
SELECT
    m.id::text,
    m.conversation_id::text,
    m.sequence_no,
    m.role,
    COALESCE(b.content, ''),
    COALESCE(m.intent, ''),
    m.status,
    m.created_at,
    m.completed_at,
    (
        SELECT count(*)
        FROM citations ci
        WHERE ci.message_id = m.id
    )::integer AS citation_count
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
LEFT JOIN message_content_blocks b
    ON b.message_id = m.id
    AND b.block_order = 0
WHERE m.conversation_id::text = $1::text
    AND c.external_user_id = $2
    AND c.deleted_at IS NULL
ORDER BY m.sequence_no
LIMIT $3 OFFSET $4
`

type ListMessagesForConversationParams struct {
	ConversationID string `json:"conversation_id"`
	ExternalUserID string `json:"external_user_id"`
	PageSize       int32  `json:"page_size"`
	PageOffset     int32  `json:"page_offset"`
}

type MessageRow struct {
	ID             string             `json:"id"`
	ConversationID string             `json:"conversation_id"`
	SequenceNo     int32              `json:"sequence_no"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Intent         string             `json:"intent"`
	Status         string             `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CitationCount  int32              `json:"citation_count"`
}

func (q *Queries) ListMessagesForConversation(ctx context.Context, arg ListMessagesForConversationParams) ([]MessageRow, error) {
	rows, err := q.db.Query(ctx, listMessagesForConversation, arg.ConversationID, arg.ExternalUserID, arg.PageSize, arg.PageOffset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]MessageRow, 0)
	for rows.Next() {
		var item MessageRow
		if err := rows.Scan(&item.ID, &item.ConversationID, &item.SequenceNo, &item.Role, &item.Content, &item.Intent, &item.Status, &item.CreatedAt, &item.CompletedAt, &item.CitationCount); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

const getMaxMessageSequence = `-- name: GetMaxMessageSequence :one
SELECT COALESCE(max(sequence_no), 0)::integer
FROM messages
WHERE conversation_id::text = $1::text
`

func (q *Queries) GetMaxMessageSequence(ctx context.Context, conversationID string) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxMessageSequence, conversationID)
	var sequence int32
	err := row.Scan(&sequence)
	return sequence, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (
    id,
    conversation_id,
    role,
    sequence_no,
    intent,
    status,
    created_at,
    completed_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    NULLIF($5, ''),
    $6,
    $7,
    CASE
        WHEN $6 = 'completed' THEN $7::timestamptz
        ELSE NULL
    END
)
`

type InsertMessageParams struct {
	ID             string    `json:"id"`
	ConversationID string    `json:"conversation_id"`
	Role           string    `json:"role"`
	SequenceNo     int32     `json:"sequence_no"`
	Intent         string    `json:"intent"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.SequenceNo,
		arg.Intent,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertMessageContentBlock = `-- name: InsertMessageContentBlock :exec
INSERT INTO message_content_blocks (
    message_id,
    block_order,
    content,
    status,
    created_at,
    updated_at
) VALUES (
    $1::uuid,
    0,
    $2,
    $3,
    $4,
    $4
)
`

type InsertMessageContentBlockParams struct {
	MessageID string    `json:"message_id"`
	Content   string    `json:"content"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertMessageContentBlock(ctx context.Context, arg InsertMessageContentBlockParams) error {
	_, err := q.db.Exec(ctx, insertMessageContentBlock, arg.MessageID, arg.Content, arg.Status, arg.CreatedAt)
	return err
}

const updateMessageStatus = `-- name: UpdateMessageStatus :execrows
UPDATE messages m
SET status = $1,
    intent = NULLIF($2, ''),
    completed_at = CASE
        WHEN $1 IN ('completed', 'failed', 'cancelled') THEN now()
        ELSE NULL
    END
FROM conversations c
WHERE m.id = $3::uuid
    AND c.id = m.conversation_id
    AND c.external_user_id = $4
    AND c.deleted_at IS NULL
`

type UpdateMessageStatusParams struct {
	Status         string `json:"status"`
	Intent         string `json:"intent"`
	ID             string `json:"id"`
	ExternalUserID string `json:"external_user_id"`
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) (int64, error) {
	tag, err := q.db.Exec(ctx, updateMessageStatus, arg.Status, arg.Intent, arg.ID, arg.ExternalUserID)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

const updateMessageContentBlock = `-- name: UpdateMessageContentBlock :exec
UPDATE message_content_blocks
SET content = $1,
    status = $2,
    updated_at = now()
WHERE message_id = $3::uuid
    AND block_order = 0
`

func (q *Queries) UpdateMessageContentBlock(ctx context.Context, content string, status string, messageID string) error {
	_, err := q.db.Exec(ctx, updateMessageContentBlock, content, status, messageID)
	return err
}

const cancelAssistantMessage = `-- name: CancelAssistantMessage :exec
UPDATE messages
SET status = 'cancelled',
    completed_at = now()
WHERE id = $1::uuid
`

func (q *Queries) CancelAssistantMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, cancelAssistantMessage, id)
	return err
}

const cancelAssistantMessageContent = `-- name: CancelAssistantMessageContent :exec
UPDATE message_content_blocks
SET status = 'cancelled',
    updated_at = now()
WHERE message_id = $1::uuid
    AND block_order = 0
`

func (q *Queries) CancelAssistantMessageContent(ctx context.Context, messageID string) error {
	_, err := q.db.Exec(ctx, cancelAssistantMessageContent, messageID)
	return err
}
