// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: model_invocations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertModelInvocation = `-- name: InsertModelInvocation :one
INSERT INTO agent_model_invocations (
    response_run_id,
    iteration_no,
    provider,
    profile_id,
    model_name,
    finish_reason,
    status,
    prompt_tokens,
    completion_tokens,
    reasoning_tokens,
    total_tokens,
    latency_ms,
    error_code,
    error_message,
    started_at,
    finished_at
) VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING id::text
`

type InsertModelInvocationParams struct {
	ResponseRunID    string             `json:"response_run_id"`
	IterationNo      int32              `json:"iteration_no"`
	Provider         string             `json:"provider"`
	ProfileID        string             `json:"profile_id"`
	ModelName        string             `json:"model_name"`
	FinishReason     pgtype.Text        `json:"finish_reason"`
	Status           string             `json:"status"`
	PromptTokens     pgtype.Int4        `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4        `json:"completion_tokens"`
	ReasoningTokens  pgtype.Int4        `json:"reasoning_tokens"`
	TotalTokens      pgtype.Int4        `json:"total_tokens"`
	LatencyMs        pgtype.Int8        `json:"latency_ms"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	StartedAt        time.Time          `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) InsertModelInvocation(ctx context.Context, arg InsertModelInvocationParams) (string, error) {
	row := q.db.QueryRow(ctx, insertModelInvocation,
		arg.ResponseRunID,
		arg.IterationNo,
		arg.Provider,
		arg.ProfileID,
		arg.ModelName,
		arg.FinishReason,
		arg.Status,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.ReasoningTokens,
		arg.TotalTokens,
		arg.LatencyMs,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listModelInvocationsByRun = `-- name: ListModelInvocationsByRun :many
SELECT
    ami.id::text,
    ami.response_run_id::text,
    ami.iteration_no,
    ami.provider,
    ami.profile_id,
    ami.model_name,
    ami.finish_reason,
    ami.status,
    ami.prompt_tokens,
    ami.completion_tokens,
    ami.reasoning_tokens,
    ami.total_tokens,
    ami.latency_ms,
    ami.error_code,
    ami.error_message,
    ami.started_at,
    ami.finished_at
FROM agent_model_invocations ami
JOIN response_runs rr ON rr.id = ami.response_run_id
JOIN conversations c ON c.id = rr.conversation_id
WHERE ami.response_run_id::text = $1::text
    AND c.external_user_id = $2
    AND c.deleted_at IS NULL
ORDER BY ami.iteration_no ASC, ami.started_at ASC
`

type ModelInvocationRow struct {
	ID               string             `json:"id"`
	ResponseRunID    string             `json:"response_run_id"`
	IterationNo      int32              `json:"iteration_no"`
	Provider         string             `json:"provider"`
	ProfileID        string             `json:"profile_id"`
	ModelName        string             `json:"model_name"`
	FinishReason     pgtype.Text        `json:"finish_reason"`
	Status           string             `json:"status"`
	PromptTokens     pgtype.Int4        `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4        `json:"completion_tokens"`
	ReasoningTokens  pgtype.Int4        `json:"reasoning_tokens"`
	TotalTokens      pgtype.Int4        `json:"total_tokens"`
	LatencyMs        pgtype.Int8        `json:"latency_ms"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	StartedAt        time.Time          `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) ListModelInvocationsByRun(ctx context.Context, responseRunID string, externalUserID string) ([]ModelInvocationRow, error) {
	rows, err := q.db.Query(ctx, listModelInvocationsByRun, responseRunID, externalUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]ModelInvocationRow, 0)
	for rows.Next() {
		var item ModelInvocationRow
		if err := rows.Scan(
			&item.ID,
			&item.ResponseRunID,
			&item.IterationNo,
			&item.Provider,
			&item.ProfileID,
			&item.ModelName,
			&item.FinishReason,
			&item.Status,
			&item.PromptTokens,
			&item.CompletionTokens,
			&item.ReasoningTokens,
			&item.TotalTokens,
			&item.LatencyMs,
			&item.ErrorCode,
			&item.ErrorMessage,
			&item.StartedAt,
			&item.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}
