// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: response_process_steps.sql

package sqlc

import (
	"context"
	"time"
)

const deleteProcessStepsByRun = `-- name: DeleteProcessStepsByRun :exec
DELETE FROM response_process_steps
WHERE response_run_id = $1::uuid
`

func (q *Queries) DeleteProcessStepsByRun(ctx context.Context, responseRunID string) error {
	_, err := q.db.Exec(ctx, deleteProcessStepsByRun, responseRunID)
	return err
}

const insertProcessStep = `-- name: InsertProcessStep :exec
INSERT INTO response_process_steps (
    id,
    response_run_id,
    step_order,
    step_type,
    label,
    detail,
    status,
    created_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertProcessStepParams struct {
	ID            string    `json:"id"`
	ResponseRunID string    `json:"response_run_id"`
	StepOrder     int32     `json:"step_order"`
	StepType      string    `json:"step_type"`
	Label         string    `json:"label"`
	Detail        string    `json:"detail"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertProcessStep(ctx context.Context, arg InsertProcessStepParams) error {
	_, err := q.db.Exec(ctx, insertProcessStep,
		arg.ID,
		arg.ResponseRunID,
		arg.StepOrder,
		arg.StepType,
		arg.Label,
		arg.Detail,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}
