// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: response_runs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const insertResponseRun = `-- name: InsertResponseRun :one
INSERT INTO response_runs (
    conversation_id,
    user_message_id,
    assistant_message_id,
    intent_type,
    route,
    status
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    NULLIF($4, ''),
    'agent',
    'running'
)
RETURNING
    id::text,
    conversation_id::text,
    user_message_id::text,
    assistant_message_id::text,
    status,
    started_at
`

type InsertResponseRunRow struct {
	ID                 string    `json:"id"`
	ConversationID     string    `json:"conversation_id"`
	UserMessageID      string    `json:"user_message_id"`
	AssistantMessageID string    `json:"assistant_message_id"`
	Status             string    `json:"status"`
	StartedAt          time.Time `json:"started_at"`
}

type InsertResponseRunParams struct {
	ConversationID     string `json:"conversation_id"`
	UserMessageID      string `json:"user_message_id"`
	AssistantMessageID string `json:"assistant_message_id"`
	IntentType         string `json:"intent_type"`
}

func (q *Queries) InsertResponseRun(ctx context.Context, arg InsertResponseRunParams) (InsertResponseRunRow, error) {
	row := q.db.QueryRow(ctx, insertResponseRun, arg.ConversationID, arg.UserMessageID, arg.AssistantMessageID, arg.IntentType)
	var item InsertResponseRunRow
	err := row.Scan(&item.ID, &item.ConversationID, &item.UserMessageID, &item.AssistantMessageID, &item.Status, &item.StartedAt)
	return item, err
}

const getResponseRunForUser = `-- name: GetResponseRunForUser :one
SELECT
    rr.id::text,
    rr.conversation_id::text,
    rr.user_message_id::text,
    rr.assistant_message_id::text,
    rr.status,
    COALESCE(rr.current_iteration, 0)::integer,
    COALESCE(rr.max_iterations, 5)::integer,
    rr.stop_reason,
    COALESCE(rr.prompt_tokens, 0) + COALESCE(rr.completion_tokens, 0) + COALESCE(rr.reasoning_tokens, 0),
    COALESCE(rr.latency_ms, 0)::bigint,
    rr.started_at,
    rr.completed_at
FROM response_runs rr
JOIN conversations c ON c.id = rr.conversation_id
WHERE rr.id::text = $1::text
    AND c.external_user_id = $2
    AND c.deleted_at IS NULL
`

type ResponseRunRow struct {
	ID                 string         `json:"id"`
	ConversationID     string         `json:"conversation_id"`
	UserMessageID      string         `json:"user_message_id"`
	AssistantMessageID string         `json:"assistant_message_id"`
	Status             string         `json:"status"`
	CurrentIteration   int32          `json:"current_iteration"`
	MaxIterations      int32          `json:"max_iterations"`
	StopReason         sql.NullString `json:"stop_reason"`
	TotalTokens        int32          `json:"total_tokens"`
	LatencyMs          int64          `json:"latency_ms"`
	StartedAt          time.Time      `json:"started_at"`
	CompletedAt        sql.NullTime   `json:"completed_at"`
}

func (q *Queries) GetResponseRunForUser(ctx context.Context, id string, externalUserID string) (ResponseRunRow, error) {
	row := q.db.QueryRow(ctx, getResponseRunForUser, id, externalUserID)
	var item ResponseRunRow
	err := row.Scan(
		&item.ID,
		&item.ConversationID,
		&item.UserMessageID,
		&item.AssistantMessageID,
		&item.Status,
		&item.CurrentIteration,
		&item.MaxIterations,
		&item.StopReason,
		&item.TotalTokens,
		&item.LatencyMs,
		&item.StartedAt,
		&item.CompletedAt,
	)
	return item, err
}

const getResponseRunIDByAssistantMessage = `-- name: GetResponseRunIDByAssistantMessage :one
SELECT rr.id::text
FROM response_runs rr
JOIN conversations c ON c.id = rr.conversation_id
WHERE rr.assistant_message_id = $1::uuid
    AND c.external_user_id = $2
`

func (q *Queries) GetResponseRunIDByAssistantMessage(ctx context.Context, assistantMessageID string, externalUserID string) (string, error) {
	row := q.db.QueryRow(ctx, getResponseRunIDByAssistantMessage, assistantMessageID, externalUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateResponseRunByAssistantMessage = `-- name: UpdateResponseRunByAssistantMessage :exec
UPDATE response_runs
SET status = $1,
    stop_reason = CASE
        WHEN $1 = 'completed' THEN NULL
        ELSE $1
    END,
    completed_at = CASE
        WHEN $1 <> 'running' THEN now()
        ELSE NULL
    END,
    latency_ms = CASE
        WHEN $1 <> 'running' THEN EXTRACT(EPOCH FROM (now() - started_at)) * 1000
        ELSE NULL
    END
WHERE assistant_message_id = $2::uuid
`

func (q *Queries) UpdateResponseRunByAssistantMessage(ctx context.Context, status string, assistantMessageID string) error {
	_, err := q.db.Exec(ctx, updateResponseRunByAssistantMessage, status, assistantMessageID)
	return err
}

const updateResponseRunIteration = `-- name: UpdateResponseRunIteration :exec
UPDATE response_runs
SET current_iteration = GREATEST(current_iteration, $1)
WHERE id = $2::uuid
`

func (q *Queries) UpdateResponseRunIteration(ctx context.Context, iterationNo int32, id string) error {
	_, err := q.db.Exec(ctx, updateResponseRunIteration, iterationNo, id)
	return err
}

const cancelResponseRun = `-- name: CancelResponseRun :one
UPDATE response_runs rr
SET status = 'cancelled',
    stop_reason = 'cancelled',
    completed_at = now(),
    latency_ms = EXTRACT(EPOCH FROM (now() - started_at)) * 1000
FROM conversations c
WHERE rr.id::text = $1::text
    AND c.id = rr.conversation_id
    AND c.external_user_id = $2
    AND c.deleted_at IS NULL
    AND rr.status IN ('running')
RETURNING rr.assistant_message_id::text
`

func (q *Queries) CancelResponseRun(ctx context.Context, id string, externalUserID string) (string, error) {
	row := q.db.QueryRow(ctx, cancelResponseRun, id, externalUserID)
	var assistantMessageID string
	err := row.Scan(&assistantMessageID)
	return assistantMessageID, err
}

const authorizeResponseRunForUser = `-- name: AuthorizeResponseRunForUser :one
SELECT true
FROM response_runs rr
JOIN conversations c ON c.id = rr.conversation_id
WHERE rr.id::text = $1::text
    AND c.external_user_id = $2
`

func (q *Queries) AuthorizeResponseRunForUser(ctx context.Context, id string, externalUserID string) (bool, error) {
	row := q.db.QueryRow(ctx, authorizeResponseRunForUser, id, externalUserID)
	var authorized bool
	err := row.Scan(&authorized)
	return authorized, err
}
