// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stream_events.sql

package sqlc

import (
	"context"
	"time"
)

const deleteStreamEventsByRun = `-- name: DeleteStreamEventsByRun :exec
DELETE FROM response_stream_events
WHERE response_run_id = $1::uuid
`

func (q *Queries) DeleteStreamEventsByRun(ctx context.Context, responseRunID string) error {
	_, err := q.db.Exec(ctx, deleteStreamEventsByRun, responseRunID)
	return err
}

const deleteToolCallsByRun = `-- name: DeleteToolCallsByRun :exec
DELETE FROM agent_tool_calls
WHERE response_run_id = $1::uuid
`

func (q *Queries) DeleteToolCallsByRun(ctx context.Context, responseRunID string) error {
	_, err := q.db.Exec(ctx, deleteToolCallsByRun, responseRunID)
	return err
}

const insertStreamEvent = `-- name: InsertStreamEvent :exec
INSERT INTO response_stream_events (
    response_run_id,
    event_seq,
    event_type,
    payload,
    created_at
) VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5
)
`

type InsertStreamEventParams struct {
	ResponseRunID string    `json:"response_run_id"`
	EventSeq      int32     `json:"event_seq"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertStreamEvent(ctx context.Context, arg InsertStreamEventParams) error {
	_, err := q.db.Exec(ctx, insertStreamEvent, arg.ResponseRunID, arg.EventSeq, arg.EventType, arg.Payload, arg.CreatedAt)
	return err
}

const upsertAgentToolCall = `-- name: UpsertAgentToolCall :exec
INSERT INTO agent_tool_calls (
    response_run_id,
    iteration_no,
    tool_call_id,
    tool_name,
    status,
    started_at,
    finished_at
) VALUES (
    $1::uuid,
    GREATEST($2, 1),
    $3,
    $4,
    $5,
    $6,
    CASE
        WHEN $5 = 'running' THEN NULL
        ELSE $6
    END
)
ON CONFLICT (response_run_id, tool_call_id) DO UPDATE SET
    status = EXCLUDED.status,
    finished_at = CASE
        WHEN EXCLUDED.status = 'running' THEN agent_tool_calls.finished_at
        ELSE EXCLUDED.finished_at
    END,
    latency_ms = CASE
        WHEN EXCLUDED.status = 'running' THEN agent_tool_calls.latency_ms
        ELSE EXTRACT(EPOCH FROM (EXCLUDED.finished_at - agent_tool_calls.started_at)) * 1000
    END
`

type UpsertAgentToolCallParams struct {
	ResponseRunID string    `json:"response_run_id"`
	IterationNo   int32     `json:"iteration_no"`
	ToolCallID    string    `json:"tool_call_id"`
	ToolName      string    `json:"tool_name"`
	Status        string    `json:"status"`
	StartedAt     time.Time `json:"started_at"`
}

func (q *Queries) UpsertAgentToolCall(ctx context.Context, arg UpsertAgentToolCallParams) error {
	_, err := q.db.Exec(ctx, upsertAgentToolCall,
		arg.ResponseRunID,
		arg.IterationNo,
		arg.ToolCallID,
		arg.ToolName,
		arg.Status,
		arg.StartedAt,
	)
	return err
}

const listStreamEventsForRun = `-- name: ListStreamEventsForRun :many
SELECT
    e.event_seq,
    e.event_type,
    e.payload,
    e.created_at
FROM response_stream_events e
JOIN response_runs rr ON rr.id = e.response_run_id
JOIN conversations c ON c.id = rr.conversation_id
WHERE rr.id::text = $1::text
    AND rr.conversation_id::text = $2::text
    AND c.external_user_id = $3
    AND c.deleted_at IS NULL
    AND e.event_seq > $4
    AND e.expires_at > now()
ORDER BY e.event_seq
`

type ListStreamEventsForRunParams struct {
	ResponseRunID  string `json:"response_run_id"`
	ConversationID string `json:"conversation_id"`
	ExternalUserID string `json:"external_user_id"`
	AfterSeq       int32  `json:"after_seq"`
}

type StreamEventRow struct {
	EventSeq  int32     `json:"event_seq"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListStreamEventsForRun(ctx context.Context, arg ListStreamEventsForRunParams) ([]StreamEventRow, error) {
	rows, err := q.db.Query(ctx, listStreamEventsForRun, arg.ResponseRunID, arg.ConversationID, arg.ExternalUserID, arg.AfterSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]StreamEventRow, 0)
	for rows.Next() {
		var item StreamEventRow
		if err := rows.Scan(&item.EventSeq, &item.EventType, &item.Payload, &item.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}
